### ISSUE TITLE
ImportError: No module named pyximport

### ISSUE THREAD

**Issue by forexhill** [wardbradt/peregrine#17]
Hi, I am running into the following;

```
~/peregrine $ python ./examples/bench.py
Traceback (most recent call last):
  File "./examples/bench.py", line 2, in <module>
    import pyximport
ImportError: No module named pyximport
```

pyximport is not listed in the requirements. I tried pip install pyximport but that did not locate such a package. Any ideas?

**Comment by wardbradt** [comment]
Have you installed Cython?

**Comment by wardbradt** [comment]
User had not installed Cython, issue will be closed.
