### ISSUE TITLE
Poor performance with utils.single_exchange.py._add_weighted_edge_to_graph()

### ISSUE THREAD

**Issue by lyn716** [wardbradt/peregrine#22]
https://github.com/wardbradt/peregrine/blob/1bb84452f8788fb43426a3919693d2977da7df9a/peregrinearb/utils/single_exchange.py#L86

Hi, wardbradt. You sent multi http requests (by coroutine) refer to single symbol ( trade pair) with ```fetch_ticker(symbol=?)``` ，then fill with weighted edge. But ```fetch_tickers()``` contains all symbols` tick info at current time.  Just one http request.

Maybe It will work.

**Comment by lyn716** [comment]
![image](https://user-images.githubusercontent.com/12389937/38599633-dd3ddf54-3d93-11e8-9e41-6fa9a561f7a4.png)
My ccxt version is 1.12.111.
Aafter executing script，I got that：
69 exchanges does not support `fetch_tickers ()` among with all 113 exchanges. And the others are ok.

**Comment by wardbradt** [comment]
Pull request has been accepted; closing issue.
