### ISSUE TITLE
Multiple coins one exchange

### ISSUE THREAD

**Issue by toanalien** [wardbradt/peregrine#27]
I run example `multiple_coins_one_exchange` on `coinexchange` exchange and got this output bellow:

```
Starting with 100 in BTC
BTC to ETC at 467.285352 = 46728.535247
ETC to RVR at 250.002500 = 11682250.634340
RVR to ETC at 0.002000 = 23364.501269
ETC to HONEY at 47.619070 = 1112595.828316
HONEY to ETC at 0.014000 = 15576.352722
ETC to ZEIT at 151285.930408 = 2356483013.976343
ZEIT to ETC at 0.000006 = 14138.898084
ETC to ETH at 0.024150 = 341.454389
ETH to LVPS at 751879.699248 = 256732623.101633
LVPS to ETC at 0.000200 = 51346.524620
ETC to BTC at 0.002120 = 108.855146
BTC to LVPS at 9090909.090909 = 989592233.275805
LVPS to ETC at 0.000200 = 197918.446655
ETC to BTC at 0.002120 = 419.589086
```
Can you expand what are `467.285352`, `250.002500`, etc. I don't think they are market's price.

Thank you.

**Comment by wardbradt** [comment]
The exchange rate (right now) from ETC to BTC is 0.00211572 as found [here](https://www.coinexchange.io/market/ETC/BTC). So, the exchange rate from BTC to ETC is the inverse of this*, roughly 472.65.

The same applies for RVR/ETC. 1 / 0.002 is equal to 500.

* Peregrine does account for the highest bid and lowest ask, but this generalization makes it easier to explain.

Note: It looks like you are using the `loop_from_source` parameter, which is currently broken. I advise you to not use it as it may or may not result in a loss.
