### ISSUE TITLE
<exchange> requires to release all resources with an explicit call to the .close() coroutine.

### ISSUE THREAD

**Issue by reteps** [wardbradt/peregrine#31]
```python3
import asyncio
from peregrinearb import load_exchange_graph, print_profit_opportunity_for_path, bellman_ford

loop = asyncio.get_event_loop()
exchange = load_exchange_graph('binance', fees=True)
graph = loop.run_until_complete(exchange)
exchange.close()

paths = bellman_ford(graph, 'BTC', unique_paths=True, loop_from_source=False, ensure_profit=True)
for path in paths:
    print_profit_opportunity_for_path(graph, path)
```

seems to be a problem with ccxt, see [this issue](https://github.com/ccxt/ccxt/issues/2092).

Trying

- `await exchange.close()` fails b/c it's not in a coroutine
- `exchange.close()` seems to do nothing.

**Comment by reteps** [comment]
possible fix: adding `await exchange.close` to `load_exchange_graph` in `single_exchange.py`

**Comment by hanyoonLDA** [comment]
Still getting `AttributeError: 'binance' object has no attribute 'close'`

**Comment by wardbradt** [comment]
Your code does not work because `load_exchange_graph` returns a DiGraph, not a ccxt exchange object.

**Comment by reteps** [comment]
How should I modify my code then? I thought load_exchange_graph was the one interacting with ccxt

**Comment by wardbradt** [comment]
Change it from:
```
loop = asyncio.get_event_loop()
exchange = load_exchange_graph('binance', fees=True)
graph = loop.run_until_complete(exchange)
exchange.close()
```
to
```
loop = asyncio.get_event_loop()
graph = loop.run_until_complete(load_exchange_graph('binance', fees=True))
```
The exchange's connection is now closed in `load_exchange_graph` so it does not have to be done manually.
