### ISSUE TITLE
Syntax error in running the first example

### ISSUE THREAD

**Issue by sompalarya1** [wardbradt/peregrine#33]
File "/home/a/PycharmProjects/untitled4/xdfg.py", line 1, in <module>
    from peregrinearb import get_opportunity_for_market
  File "/usr/local/lib/python3.5/dist-packages/peregrinearb/__init__.py", line 1, in <module>
    from .async_find_opportunities import OpportunityFinder, get_opportunity_for_market
  File "/usr/local/lib/python3.5/dist-packages/peregrinearb/async_find_opportunities.py", line 54
    [await self._test_bid_and_ask(exchange_name) for exchange_name in self.exchange_list]
            ^
SyntaxError: 'await' expressions in comprehensions are not supported

**Comment by wardbradt** [comment]
If you are talking about this example:
```
from peregrinearb import get_opportunity_for_market
import asyncio
opportunity = asyncio.get_event_loop().run_until_complete(get_opportunity_for_market("BTC/USD"))
print(opportunity)
```
I just looked at it. I did not get the error you did. However, I did run into some similar problems which I have just fixed [here](https://github.com/wardbradt/peregrine/commit/09f9c4d8390bbe848acbd86d8e194fcea299073d).
