### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by Chriskatz** [wardbradt/peregrine#41]
from peregrinearb import create_weighted_multi_exchange_digraph, bellman_ford_multi, print_profit_opportunity_for_path_multi

graph = create_weighted_multi_exchange_digraph(['exmo', 'binance', 'bitmex', 'bittrex', 'gemini', 'kraken'], log=True)

graph, paths = bellman_ford_multi(graph, 'ETH', unique_paths=True)
for path in paths:
    print_profit_opportunity_for_path_multi(graph, path)

=============================================================
D:\python mutiexchangecurrency.py
  
Task exception was never retrieved
future: <Task finished coro=<_add_market_to_multi_digraph() done, defined at C:\Python36\lib\site-packages\peregrinearb\utils\multi_exchange.py:93> exception=TypeError("unsupported operand type(s) for *: 'int' and 'NoneType'",)>
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\peregrinearb\utils\multi_exchange.py", line 130, in _add_market_to_multi_digraph
    weight=-math.log(fee_scalar * ticker_bid))
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
Task exception was never retrieved
future: <Task finished coro=<_add_market_to_multi_digraph() done, defined at C:\Python36\lib\site-packages\peregrinearb\utils\multi_exchange.py:93> exception=TypeError("unsupported operand type(s) for *: 'int' and 'NoneType'",)>
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\peregrinearb\utils\multi_exchange.py", line 130, in _add_market_to_multi_digraph
    weight=-math.log(fee_scalar * ticker_bid))
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

**Comment by wardbradt** [comment]
Closed due to inactivity
