### ISSUE TITLE
RuntimeError: shutdown in progress on Raspberry Pi

### ISSUE THREAD

**Issue by xCuri0** [wardbradt/peregrine#42]
I get the error ```RuntimeError: shutdown in progress``` when running it on a Raspberry Pi with Raspbian with Python 3.5. Doesn't happen on my laptop with Python 3.7

**Comment by wardbradt** [comment]
Could you post what code you are running? And what version of `peregrine`?

**Comment by xCuri0** [comment]
@wardbradt the bot sample with a few changes (like check if a buy or sell order is needed). And the latest version from this repo

**Comment by xCuri0** [comment]
@wardbradt Installed Ubuntu server on the Pi and it doesn't happen. The issue is limited to Raspbian only

**Comment by xCuri0** [comment]
@wardbradt 3.6
