### ISSUE TITLE
Setting starting currency no longer works.

### ISSUE THREAD

**Issue by hanyoonLDA** [wardbradt/peregrine#49]
Been a while since I played with this project. One issue I'm running into, which wasn't a problem before, is that setting the starting currency for one exchange, multiple coins seems to no longer work properly. 

Whether its 

`paths = bellman_ford(graph, 'BTC', unique_paths=True)`
or
`paths = bellman_ford(graph, 'ETH', unique_paths=True)`

or any currency I put, it seems that the starting currency is different everytime depending on the current opportunities.

**Comment by wardbradt** [comment]
Hi,
Bellman Ford finds opportunities which are reachable from a currency. It does not find opportunities containing a currency. If an opportunity is found containing a currency you would like to start from, it can be easily be done by rotating the list of currencies.

**Comment by wardbradt** [comment]
Can I close this?

**Comment by parthi2929** [comment]
Hi

If so, what is the purpose of that currency input?

**Comment by hanyoonLDA** [comment]
> Hi
> 
> If so, what is the purpose of that currency input?

Wondering the same thing...
