### ISSUE TITLE
How to save the bellman_ford algorithm running time ？ thanks.

### ISSUE THREAD

**Issue by littleworm2018** [wardbradt/peregrine#50]
Hi, Thank you for your work.
In One Exchange/ Multiple Currencies，if find a first path of setting profit （like large than 1%），how to stop the function of bellman_ford  and return the path？  （I want to save algorithm time）
thanks.

**Comment by hanyoonLDA** [comment]
Not sure what you are trying to achieve here, can you clarify? You want to stop the script everytime a certain threshold of profit is met? My suggestion would be save the path and have a secondary script take care of performing the arbitrage buys, while keep the script running.

**Comment by wardbradt** [comment]
I am closing the issue as it is unclear what the problem is or what functionality is desired. Please open a new issue if you are still interested in changes to the project.
