### ISSUE TITLE
Duplicate outputs for multi exchange

### ISSUE THREAD

**Issue by parthi2929** [wardbradt/peregrine#53]
Hi

For below combination of exchanges, I am getting CBT/ETH pair, same message printed over multiple times (screen shot below shows only part of it due to space)

**Code:**  
```python
from peregrinearb import create_weighted_multi_exchange_digraph, bellman_ford_multi, print_profit_opportunity_for_path_multi


graph = create_weighted_multi_exchange_digraph(['bitfinex', 'huobiru', 'okex'], log=True, fees=True)
graph, paths = bellman_ford_multi(graph, 'ETH')
for path in paths:
    print_profit_opportunity_for_path_multi(graph, path)
```

**Output:**  
![image](https://user-images.githubusercontent.com/11896263/57570949-3303a680-7425-11e9-94ac-488e64f710ff.png)

**Comment by wardbradt** [comment]
I am now fixing several of the issues with the project as I have some free time this week. I will look into this one.

**Comment by wardbradt** [comment]
`unique_paths` defaulted to False, which caused this behavior. Fixed on the dev branch in https://github.com/wardbradt/peregrine/pull/61.
