### ISSUE TITLE
Ignored Precision limitations could create deceptive gains

### ISSUE THREAD

**Issue by parthi2929** [wardbradt/peregrine#56]
Hi

Exchanges have precision limitations which are not taken care in the calculation, but might affect the output. Can you please include them? As that could mean, significant loss in certain coins. 

![image](https://user-images.githubusercontent.com/11896263/57612171-f43f2f00-7591-11e9-82c6-33aae89709a0.png)

[Here](https://support.bitfinex.com/hc/en-us/articles/115000371105-How-is-precision-calculated-using-Significant-Digits) is the precision limits link for coins in bitfinex exchange. They use only 5 significant digits.  

If its difficult to include for all exchanges, at least you could provide an option to let us specify some where.

**Comment by vxnuke** [comment]
Looks like changes need to be made in utils/general.py ill have another go at it tomorrow. New to this project.
