### ISSUE TITLE
import asyncio errors

### ISSUE THREAD

**Issue by MiningAmazing** [wardbradt/peregrine#58]
When I want to import asyncio I get next error message:

"import-im6.q16: not authorized `asyncio' @ error/constitute.c/WriteImage/1037"

The solution in https://github.com/wardbradt/peregrine/issues/16 doesn't help or I don't know how it would help me.

Any suggestion please?

Thanks!

**Comment by hanyoonLDA** [comment]
What Python version are you using?

**Comment by MiningAmazing** [comment]
Python 2.7.15+

[image: image.png]

Thanks!

Missatge de Lunar Digital Assets <notifications@github.com> del dia dg., 4
d’ag. 2019 a les 9:45:

**Comment by hanyoonLDA** [comment]
You'll need Python 3.7 to properly run async.

**Comment by MiningAmazing** [comment]
Ok,

I'll try and let you know the results.

Thanks!
