### ISSUE TITLE
utils.logging_utils

### ISSUE THREAD

**Issue by gitcoo** [wardbradt/peregrine#59]
Hi and thanks for the cool software!

I am getting this:

ModuleNotFoundError: No module named 'utils.logging_utils'

When I do this:

pip install utils.logging_utils

I get this:

No matching distribution found for utils.logging_utils

Would you have any suggestion for this? Thank you! :D

$ python
Python 3.6.8 (default, Apr  9 2019, 04:59:38) 
[GCC 8.3.0] on linux

**Comment by wardbradt** [comment]
I am now fixing several of the issues with the project as I have some free time this week. Some relative imports, such as this one, are errant. I will fix this.

**Comment by wardbradt** [comment]
Fixed in https://github.com/wardbradt/peregrine/pull/61
