### ISSUE TITLE
AttributeError: 'MultiDiGraph' object has no attribute 'edge_bunches'

### ISSUE THREAD

**Issue by ymovlian** [wardbradt/peregrine#60]
Hello,

I'm trying to run Multiple Exchanges/ Multiple Currencies example from the README and get the following error:

```
$ python3 script.py 
Traceback (most recent call last):
  File "peregrine.py", line 6, in <module>
    for path in paths:
  File "/home/username/.local/lib/python3.7/site-packages/peregrinearb/bellman_multi_graph.py", line 20, in bellman_ford
    self._first_iteration()
  File "/home/username/.local/lib/python3.7/site-packages/peregrinearb/bellman_multi_graph.py", line 43, in _first_iteration
    [self._process_edge_bunch(edge_bunch) for edge_bunch in self.graph.edge_bunches(data=True)]
AttributeError: 'MultiDiGraph' object has no attribute 'edge_bunches'

```

I'm using dev branch.

**Comment by wardbradt** [comment]
You have to run `pip install git+https://github.com/wardbradt/networkx`. This is undocumented and is a problem with the requirements.txt file. I will fix it.

**Comment by al3github** [comment]
Hi, I am having the same problem as @packetlife and I have networkx (2.5) installed. When I went to check the MultiDiGraph code, I saw that indeed this class has no attribute 'edge_bunches'.

**Comment by edouardkombo** [comment]
This fix is addressed here https://github.com/wardbradt/peregrine/pull/76

@wardbradt could you please accept the pull request?
