### ISSUE TITLE
Module missing

### ISSUE THREAD

**Issue by MiningAmazing** [wardbradt/peregrine#70]
Hi,

Using python 3.8.6 and Peregrine 1.8.0 (I think...) I get next error when executing the code in the example **_multiple_coins_multiple_exchanges.py_**:

**ModuleNotFoundError: No module named 'networkx'**

Can you please explain how can I install it or if I'm doing something wrong?

Thank you

**Comment by hanyoonLDA** [comment]
`sudo pip3 install networkx` should do it.

**Comment by MiningAmazing** [comment]
It worked.

thanks!
